menu:
- {name: 'people', url: '/people'}
- {name: 'publications & talks', url: '/publications'}
- {name: 'press', url: '/press'}
# - {name: 'cv', url: '/cv'}
- {name: 'courses', url: '/courses'}
- {name: 'contact', url: '/contact'}

#need talks, events and PROJECTS
courses:
- {name: 'Translational Neuroscience (GM51075)', url: 'https://www.dundee.ac.uk/module/gm51075'}
#- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
#- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'fab fa-github', link: 'https://github.com/tom-gilbertsons-lab'}
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'fa fa-graduation-cap', link: 'https://www.dundee.ac.uk/people/tom-gilbertson'}
- {icon: 'fa fa-book-open', link: 'https://discovery.dundee.ac.uk/en/persons/tom-gilbertson'}
# - {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}


contacts:
- {name: 'Dr Tom Gilbertson',
  role1: 'Senior Lecturer',  department1: 'Neuroscience', institution1: 'School of Medicine, University of Dundee',
  role2: 'Honorary Consultant',  department2: 'Neurology', institution2: 'NHS Tayside',
  institution_address: 'Ninewells Hospital & Medical School, Dundee',
  email: 't.gilbertson@dundee.ac.uk', office: 'Lab Block L6 C 044',
  image: 'assets/img/contact.png', url: 'tom-gilbertson'}
